from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
from langchain.vectorstores import DeepLake
from langchain.embeddings.sentence_transformer import SentenceTransformerEmbeddings
